site_name: "API Generation"
site_url: "https://apigeneration.tech/" # Update with your URL
repo_url: "https://github.com"

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette: 
    # Optional styling: Automatically switches between light and dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs      # Top-level horizontal menu tabs
    - navigation.sections  # Left sidebar grouping collapse
    - search.suggest       # Smart search bar autocompletion

# Organise your pages here. The files must exist inside the /docs folder.
nav:
  - Home: index.md
  - Learn:
    - MTT Overview: learn/mtt-overview/index.md
    - Projects: learn/projects/index.md
    - Models: learn/models/index.md
    - Loaders: learn/loaders/index.md
    - Standard Generators: learn/standard-generators/index.md
    - New Generators: learn/new-generators/index.md
    - Running MTT: learn/running-mtt/index.md
    - Example Projects: learn/example-projects/index.md
  - Try MTT: try-mtt/index.md
#  - Contact Us: contact.md

